### ISSUE TITLE
Eslint issue for imported modules

### ISSUE THREAD

**Issue by RubenWalraevens** [dealloc/webpack#1]
How to recreate the problem.

```ssh
npm install --save semantic-ui
```

in src/js/index.js:
```js
import '../../semantic/dist/semantic.min';
import '../../semantic/dist/semantic.min.css';
```

And now he starts bitching about wrong function names and so on.

**Comment by dealloc** [comment]
You'll have to give a little more information about the "_bitching_" part I'm afraid
